# Generated by Django 5.1.1 on 2024-10-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sweet_shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sweet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sweet_shared.sweettype')),
            ],
        ),
    ]
